#  01 Prepare Problem 
## a) Load packages {@a) Load packages}
```{r load_project_packages, message=FALSE, warning=FALSE}
# Install package with dependencies
#install.packages("caret", dependencies = c("Depends", "Suggests"))
packages <- c("tidyverse", "ggplot2", "caret", "mlbench", "caretEnsemble", "ipred", "rpart","doMC", "AppliedPredictiveModeling", "corrplot", "Hmisc", "DMwR", "lattice",
	"RWeka", "e1071", "C50", "andrews", "kohonen")

for (p in packages) {
	if(p %in% rownames(installed.packages()) == FALSE) {
		install.packages(p, repos=repository)
	}
}
```

## b) Load dataset {@b) Load dataset}
```{r load_data_packages, message=FALSE, warning=FALSE}
# Datasets from the mlbench library

# load the library
library(mlbench)

# list the contents of the library
#library(help = "mlbench")

# Boston Housing dataset
data(BostonHousing)
#dim(BostonHousing)
#head(BostonHousing)

# Wisconsin Breast Cancer dataset
data(BreastCancer)
#dim(BreastCancer)
#levels(BreastCancer$Class)
#head(BreastCancer)

# Glass Identification dataset
data(Glass)
#dim(Glass)
#levels(Glass$Type)
#head(Glass)

# Johns Hopkins University Ionosphere dataset
data(Ionosphere)
#dim(Ionosphere)
#levels(Ionosphere$Class)
#head(Ionosphere)

# Pima Indians Diabetes dataset
data(PimaIndiansDiabetes)
#dim(PimaIndiansDiabetes)
#levels(PimaIndiansDiabetes$diabetes)
#head(PimaIndiansDiabetes)

# Sonar, Mines vs. Rocks dataset
data(Sonar)
#dim(Sonar)
#levels(Sonar$Class)
#head(Sonar)

# Soybean dataset
data(Soybean)
#dim(Soybean)
#levels(Soybean$Class)
#head(Soybean)
#
# Datasets from the AppliedPredictiveModeling library

# load the library
library(AppliedPredictiveModeling)

# list the contents of the library
#library(help = "AppliedPredictiveModeling")

# Abalone Data
data(abalone)
dim(abalone)
head(abalone)

# Datasets from the dataset library

# list the contents of the library
#library(help = "datasets")
library('datasets')
# list all available datasets in all loaded libraries
data()

# Iris flowers datasets
data(iris)
dim(iris)
levels(iris$Species)
head(iris)

# Longley's Economic Regression Data
data(longley)
dim(longley)
head(longley)

# Load data from a CSV file in the local directory
# define the filename
# filename <- "/Users/tymen/RHome/machine_learning_mastery_with_r/code/1-AnalyzeData/1-LoadData/iris.csv"
# # load the CSV file from the local directory
# dataset <- read_csv(filename)
# preview the first 5 rows
#head(dataset)

# Load CSV From a URL

# load the library
library(RCurl)
# specify the URL for the Iris data CSV
urlfile <-'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# download the file
downloaded <- getURL(urlfile, ssl.verifypeer=FALSE)
# treat the text data as a steam so we can read from it
connection <- textConnection(downloaded)
# parse the downloaded data as CSV
dataset <- read.csv(connection, header=FALSE)
# preview the first 5 rows
head(dataset)

```
## c) Split-out validation dataset {@c) Split-out validation dataset}
